### ISSUE TITLE
Cluster 0 times out and then becomes ready

### ISSUE THREAD

**Issue by pizzafox** [Dev-Yukine/Kurasuta#103]
After upgrading to `0.2.17` this started happening. Cluster 0 appears to become ready after it says it took to long to become ready, what's happening here?
```js
[3/22/2019] [4:59:11 AM] [shard manager] › ⬤  debug Shard 0 became ready
[3/22/2019] [5:00:50 AM] [shard manager] › ⬤  debug Shard 2 became ready
[3/22/2019] [5:01:06 AM] [shard manager] › ✖  fatal An error occurred when spawning clusters
[3/22/2019] [5:01:06 AM] [shard manager] › ✖  error Error: Cluster 0 took too long to get ready
    at Timeout.setTimeout [as _onTimeout] (/usr/src/dice/node_modules/.registry.npmjs.org/kurasuta/0.2.17/node_modules/kurasuta/dist/Cluster/Cluster.js:72:37)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
[3/22/2019] [5:01:25 AM] [shard manager] › ⬤  debug Shard 1 became ready
[3/22/2019] [5:01:34 AM] [shard manager] › ⬤  debug Shard 3 became ready
[3/22/2019] [5:01:39 AM] [shard manager] › ⬤  debug Cluster 0 became ready
```

**Comment by Dev-Yukine** [comment]
this seems like your cluster takes more then 30 seconds * shardCount for Cluster zero to get ready, this could be related to either your code to run that long and block or (most likely) d.js isn't emitting ready on that cluster for some reason

**Comment by Dev-Yukine** [comment]
if you wish to manually increase this timeout, you can do with Sharderoptions#timeout which is now documented as of b3874502facfac9b47e5281681f36ff480f23c31
